### 2 - Numpy
#### Numpy Fundamentals 

#### Numpy Arrays

In [1]:
#import the numpy library
import numpy as np

In [2]:
#create a numpy array
mylist = [1,2,3]
newlist = np.array(mylist)
print(newlist)
type(newlist)


[1 2 3]


numpy.ndarray

In [3]:
my_matrix = [[1,2,3],[4,5,6], [7,8,9]]
new_matrix = np.array(my_matrix)
new_matrix


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
#np range from 0 to 100
a = np.arange(0,100)
#step size of 5
b = np.arange(0,100, 5)
print(a)
print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [5]:
#zeros
np.zeros(6)

array([0., 0., 0., 0., 0., 0.])

In [6]:
#2d zeros array
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [7]:
np.ones((5,10))

array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [8]:
#linspace
np.linspace(0, 20, 6)

array([ 0.,  4.,  8., 12., 16., 20.])

In [10]:
#np eye for identity matrix
np.eye(10)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [16]:
#random number distributions
j = np.random.rand(5,6)
print(j)


[[0.15714587 0.90563386 0.64599379 0.27101131 0.28941654 0.86147525]
 [0.78767217 0.65662183 0.06109368 0.80812567 0.80923464 0.04596422]
 [0.80100054 0.48227713 0.78795356 0.10606795 0.20876838 0.20764393]
 [0.54849419 0.87589672 0.91309804 0.9054479  0.98971242 0.68919465]
 [0.54661507 0.34570957 0.7527344  0.62841355 0.78539207 0.11592852]]


In [20]:
#standard normal distribution, where we can get negative numbers
np.random.randn(2, 3)

array([[ 1.40674049, -0.53831382, -1.48549981],
       [ 0.08711057,  0.12612252, -1.83326302]])

In [24]:
#random integer, returns back from low to high and numbers have the same likelyhood
np.random.randint(0, 101, (3,3))

array([[24, 83, 78],
       [87, 98, 28],
       [48, 49, 91]])

In [30]:
#set a seed, random state, where we can repeat random numbers
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [38]:
#arange function
arr = np.arange(0,25)
#reshape the array
k = arr.reshape(1,25)
k

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [53]:
#argmax and argmin
ranarr = np.random.randint(0, 101, 10)
print(ranarr)
#find max value using.max and min value using .min
e = ranarr.max()
f = ranarr.min()
print(e)
print(f)

[84 79 81 52 23 25 88 59 40 28]
88
23


In [54]:
#find index location using argmax()
ranarr.argmax()

6

In [55]:
#find datatype
ranarr.dtype

dtype('int32')

In [57]:
#find shape
ranarr.shape

(10,)

#### Numpy indexing and Selection

In [61]:
arr1 = np.arange(0,11)
#get value of 8
o = arr1[8]

8


In [62]:
#slicing 1 to 5
arr1[1:5]

array([1, 2, 3, 4])

In [63]:
#slice from 0 
arr1[:5]

array([0, 1, 2, 3, 4])

In [65]:
#slice and start from 5 to the end
arr1[5:]

array([ 5,  6,  7,  8,  9, 10])

In [70]:
#slicing a section an array and act as a pointer 
slice_of_arr = arr[0:5]
#convert all of those into 99
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [71]:
#original array has been affected
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [72]:
#selection
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [74]:
#select single row
arr_2d[2]

array([35, 40, 45])

In [76]:
#select single element, grab element from row 2, column 0
arr_2d[2, 0]

35

In [79]:
#select specific rows
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [81]:
#condition selection
arr2 = np.arange(1,11)
#true or false that each number is greater than 4
arr2 > 4

array([False, False, False, False,  True,  True,  True,  True,  True,
        True])

In [85]:
#filter out
bool_arr = arr2 > 4
arr2[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [94]:
#exercise 2
#Use numpy to check how many rolls were greater than 2. For example if dice_rolls=[1,2,3] then the answer is 1.
dice_rolls = np.array([3, 1, 5, 2, 5, 1, 1, 5, 1, 4, 2, 1, 4, 5, 3, 4, 5, 2, 4, 2, 6, 6, 3, 6, 2, 3, 5, 6, 5])

total_rolls_over_two = dice_rolls > 2

print(len(dice_rolls[total_rolls_over_two]))
#answer is 19

19


#### Numpy Operations

In [95]:
#arithmetic operations between arrays
arr3 = np.arange(0,10)
#adds 5 to every number in array
#can be done with all operations
arr3 + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [96]:
#multiply array by each other
arr3*arr3

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [97]:
#divide by zero = inf
1/ arr3

C:\Users\Armand S\AppData\Local\Temp\ipykernel_13224\2385394550.py:2: RuntimeWarning: divide by zero encountered in divide
  1/ arr3


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [98]:
#sqrt
np.sqrt(arr)

array([9.94987437, 9.94987437, 9.94987437, 9.94987437, 9.94987437,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
       3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894,
       4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949])

In [99]:
#trigonometric functions
np.sin(arr3)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [100]:
#sum in np
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [102]:
#rows are represented by axis = 0
#perform this operation across these rows
arr_2d.sum(axis=0)

array([60, 75, 90])

In [103]:
arr_2d.sum(axis=1)

array([ 30,  75, 120])

#### Exercise 3

In [104]:
#Use numpy to check the total remaining in the account after the series of transactions.
account_transactions = np.array([100,-200,300,-400,100,100,-230,450,500,2000])
account_transactions.sum()
#answer is 2720


2720